GET http://localhost:3000/api/products

###

http://localhost:3000/api/products/v2

###

GET localhost:3000/api/products/cat/oficina

###

GET http://localhost:3000/api/products/2

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "cantimplora azul",
  "description": "cantimplora de montaña",
  "price": 10,
  "category": "aventura"
}

###

PUT http://localhost:3000/api/products

###

DELETE http://localhost:3000/api/products